version: '3.1'
services: 
    homeassistant:
        build: .
        ports:  
            - 8123:8123
    consul:
        container_name: consul
        image: consul:latest
        ports: 
            - 8500:8500
            - 8600:8600
            - 8400:8400
