catalog_register:
  description: A a low level mechanism for directly registering or updating entries in the catalog.
  fields:
    host:
      name: Host
      description: The host
      example: 192.168.0.21
      required: true
      selector:
        text:

    port:
      name: Port
      description: The port
      example: 8500
      required: false
      selector:
        text:

    protocol:
      name: Protocol
      description: The protocol HTTP or HTTPS
      example: http
      required: false
      selector:
        text:

    token:
      name: Token
      description: The token
      example: 57c5d69a-5f19-469b-0543-12a487eecc66
      required: true
      selector:
        text:

    datacenter:
      name: Datacenter
      description: The datacenter
      example: prod
      required: false
      selector:
        text:

    node:
      name: Node
      description: The node name
      example: raspberry
      required: true
      selector:
        text:

    id:
      name: ID Node
      description: ID Node
      example: 22ed1a08-cfe8-4833-b8a0-945a0264beb6
      required: false
      selector:
        text:

    address:
      name: Address
      description: The address node
      example: 192.168.0.1
      required: true
      selector:
        text:

    taggedaddresses:
      name: TaggedAddresses
      description: Specifies the tagged addresses.
      example: {}
      required: false
      selector:
        object:

    node_meta:
      name: node
      description: Specifies arbitrary KV metadata pairs for filtering purposes.
      example: {}
      required: false
      selector:
        object:

    service:
      name: Service
      description: Specifies to register a service
      example: {}
      required: false
      selector:
        object:

    check:
      name: Check
      description: Specifies to register a check
      example: {}
      required: false
      selector:
        object:

catalog_deregister:
  description: Directly remove entries in the catalog.
  fields:
    host:
      name: Host
      description: The host
      example: 192.168.0.21
      required: true
      selector:
        text:

    port:
      name: Port
      description: The port
      example: 8500
      required: false
      selector:
        text:

    token:
      name: Token
      description: The token
      example: 57c5d69a-5f19-469b-0543-12a487eecc66
      required: true
      selector:
        text:

    node:
      name: Node
      description: The node name
      example: raspberry
      required: true
      selector:
        text:

    datacenter:
      name: Datacenter
      description: The datacenter
      example: prod
      required: false
      selector:
        text:

    service_id:
      name: Service ID
      description: The service id
      example: freepbx
      required: false
      selector:
        text:

    check_id:
      name: Check ID
      description: The check id
      example: service:freepbx
      required: false
      selector:
        text:

    ns:
      name: Namesspace
      description: Namespace
      example: team-1
      required: false
      selector:
        text:

kv_create_or_update:
  description: The /kv endpoints access Consul's simple key/value store, useful for storing service configuration or other metadata
  fields:
    host:
      name: Host
      description: The host
      example: 192.168.0.21
      required: true
      selector:
        text:

    port:
      name: Port
      description: The port
      example: 8500
      required: false
      selector:
        text:

    token:
      name: Token
      description: The token
      example: 57c5d69a-5f19-469b-0543-12a487eecc66
      required: true
      selector:
        text:

    key:
      name: Key
      description: Specifies the path of the key.
      example: jadson179
      required: true
      selector:
        text:

    value:
      name: Value
      description: The payload is arbitrary, and is loaded directly into Consul as supplied.
      example: https://github.com/jadson179
      required: true
      selector:
        text:
          multiline: true

    datacenter:
      name: Datacenter
      description: The datacenter
      example: prod
      required: false
      selector:
        text:

    flags:
      name: Flags
      description: Specifies an unsigned value between 0 and (2^64)-1.
      example: 0
      required: false
      selector:
        text:

    cas:
      name: Cas
      description: Specifies to use a Check-And-Set operation.
      example: 0
      required: false
      selector:
        text:

    acquire:
      name: Acquire
      description: Supply a session ID to use in a lock acquisition operation.
      example: ""
      required: false
      selector:
        text:

    release:
      name: Release
      description: Supply a session ID to use in a release operation.
      example: ""
      required: false
      selector:
        text:

    ns:
      name: Namespace
      description: Specifies the namespace to query.
      example: default
      required: false
      selector:
        text:

kv_delete:
  description: This endpoint deletes a single key or all keys sharing a prefix.
  fields:
    host:
      name: Host
      description: The host
      example: 192.168.0.21
      required: true
      selector:
        text:

    port:
      name: Port
      description: The port
      example: 8500
      required: false
      selector:
        text:

    token:
      name: Token
      description: The token
      example: 57c5d69a-5f19-469b-0543-12a487eecc66
      required: true
      selector:
        text:

    key:
      name: Key
      description: Specifies the path of the key.
      example: jadson179
      required: true
      selector:
        text:

    datacenter:
      name: Datacenter
      description: The datacenter
      example: prod
      required: false
      selector:
        text:

    recurse:
      name: Recurse
      description: Specifies to delete all keys which have the specified prefix.
      example: False
      required: false
      selector:
        boolean:

    cas:
      name: Cas
      description: Specifies to use a Check-And-Set operation.
      example: 0
      required: false
      selector:
        text:

    ns:
      name: Namespace
      description: Specifies the namespace to query.
      example: default
      required: false
      selector:
        text:
