name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate_hacs:
    name: "HACS Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
  validate_hassfest:
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: home-assistant/actions/hassfest@master
  tests:
    name: "Stack Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
    run: docker-compose up -d consul
      - name: Sleep
    uses: jakejarvis/wait-action@master
    with:
    time: '60s'
      - name: Check running containers
    run: docker ps
      - name: Run test suite
      - uses: actions/checkout@master
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@master
        with:
          args: pytest .